# Generated by Django 3.0.5 on 2020-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=20)),
                ('ivr_code', models.CharField(max_length=10)),
            ],
        ),
    ]
