# Generated by Django 3.0.5 on 2020-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugNotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
