# Generated by Django 3.0.5 on 2020-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugNotify', '0006_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ManyToManyField(related_name='tests', related_query_name='test', to='DrugNotify.User'),
        ),
    ]
