# Generated by Django 3.0.5 on 2020-12-01 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugNotify', '0008_auto_20201201_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_checked',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
