# Generated by Django 3.0.5 on 2020-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugNotify', '0009_auto_20201201_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_checked',
            field=models.DateField(),
        ),
    ]
