# Generated by Django 3.0.5 on 2021-03-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugNotify', '0010_auto_20201201_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
