# Generated by Django 3.2.4 on 2021-06-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugNotify', '0012_auto_20210622_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_morning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_noon',
            field=models.BooleanField(default=True),
        ),
    ]
