# Generated by Django 3.2.4 on 2021-06-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrugNotify', '0013_auto_20210622_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
